

CREATE   view [dbo].[SystemTest5] 
as with 
cte5 as (
select N'EconomistBourseUSDovJones.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'BoursUSDovJones' [به کجا ارسال میشود], N'VBoursUSDovJones' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from BoursUSDovJones order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/united-states/stock-market' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInBoursEnglis]
union all 
select N'EconomistGardeshSarmaye.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'GardeshSarmaye' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from GardeshSarmaye order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/capital-flows' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInGardeshSarmaye]
union all 
select N'EconomistHadeAghalDastmozd.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'HadeAghalDastmozd' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from HadeAghalDastmozd order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/minimum-wages' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInHadeAghalDastmozd]
union all 
select N'با احتساب دوره های انشتار اطلاعات،‌نهایتا مه کشورها به دوره های یک ماهه تبدیل شدند' [اولین توضیح], N'HesabeJariEconomist.py' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'KasriHesabeJari' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from KasriHesabeJari order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/current-account' [کجا را میخواند], 'HesabeJariHistory.xlsx' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInKasriHesabeJari]
union all 
select N'ارتباطات نا مشروع' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'' [به کجا ارسال میشود], N'-',N'-',N'-',N'-',N'-',N'-',N'-',N'-',N'',N'', N'HesabeJariHistory.xlsx' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
union all 
select N'EconomistMaliatBarDaramadShakhsi.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'MaliatBarDaramadShakhsi' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from MaliatBarDaramadShakhsi order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/personal-income-tax-rate' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInMaliatBarDaramadShakhsi]
union all 
select N'EconomistMaliatBarSherkatHa.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'MaliatBarSherkatHa' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from MaliatBarSherkatHa order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/corporate-tax-rate' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInMaliatBarSherkatHa]
union all 
select N'Economist-m2.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'Naghdinegi' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from Naghdinegi order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/money-supply-m2' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInNaghdinegi]
union all 
select N'EconomistNerkheBahreBanki.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'NerkheBahreBanki' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from NerkheBahreBanki order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/deposit-interest-rate' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInNerkheBahreBanki]
union all 
select N'EconomistNerkheVaamBanki.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'NerkheVaamBanki' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from NerkheVaamBanki order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/bank-lending-rate' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInNerkheVaamBanki]
union all 
select N'EconomistPasandazAshkhas.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'PasandazShakhsi' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from PasandazShakhsi order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/personal-savings' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInPasandazShakhsi]
union all 
select N'EconomistSarmayeGozariKhareji.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'SarmayeGozariKhareji' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from SarmayeGozariKhareji order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/foreign-direct-investment' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInSarmayeGozariKhareji]
union all 
select N'EconomistShakhesMaskan.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'ShakhesMaskan' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from ShakhesMaskan order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/housing-index' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInShakhesMaskan]
union all 
select N'EconomistTolidKhodro.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'TolidKhodro' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from TolidKhodro order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/car-production' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInTolidKhodro]
union all 
select N'EconomistTolidNaftKhaam.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'TolidNaftKhaam' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from TolidNaftKhaam order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/crude-oil-production' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInTolidNaftKhaam]
union all 
select N'EconomistTolidNakhalesDakheli.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'TolidNakhalesDakheli' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from TolidNakhalesDakheli order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/gdp' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInTolidNakhalesDakheli])
select * 
from cte5
