

CREATE   view [dbo].[SystemTest2]
as with 
cte as(

select N'BalancSheetGheyreTalfighi_DataBase_incomeStatement_FaraBourse.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'BalanceSheetGheyreTalfighiCategurincomestatement_FaraBourse' [به کجا ارسال میشود], N'https://api.bourseview.com/v2/stocks/statements' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180, (select top 1 cast(createdate as nvarchar(20)) from [BalanceSheetGheyreTalfighiCategurincomestatement_FaraBourse] order by createdate desc) [آخرین زمان بروز رسانی],N''[A], N'' [کجا را میخواند], '' [کجا را میخواند دوم], N' اینکام استیت منت غیر تلفیقی فرابورس' [کاربرد]
from [P_CalcDayCountInBalanceSheetGheyreTalfighiCategurincomestatement_FaraBourse]
union all 
select N'BalancSheetTalfighi_DataBase_BalancSheet_Bourse.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'[BalanceSheetTalfighiCategurbalancesheet_Bourse]' [به کجا ارسال میشود], N'https://api.bourseview.com/v2/stocks/statements',cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180, (select top 1 cast(createdate as nvarchar(20)) from [BalanceSheetTalfighiCategurbalancesheet_Bourse] order by createdate desc) [آخرین زمان بروز رسانی],N'', N'' [کجا را میخواند], '' [کجا را میخواند دوم], N' بالانس شیت تلفیقی بورس' [کاربرد]
from P_CalcDayCountInBalanceSheetTalfighiCategurbalancesheet_Bourse
union all 
select N'BalancSheetTalfighi_DataBase_BalancSheet_FaraBourse.py' [اولین توضیح], N'تلفیقی های فرابورس باید چهار ماه گذشته شان فراخوانی شود تا بورس ویو داده بیاورد'  [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'[BalanceSheetTalfighiCategurbalancesheet_Bourse]' [به کجا ارسال میشود], N'https://api.bourseview.com/v2/stocks/statements',cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180, (select top 1 cast(createdate as nvarchar(20)) from [BalanceSheetTalfighiCategurbalancesheet_FaraBourse] order by createdate desc) [آخرین زمان بروز رسانی],N'', N'' [کجا را میخواند], '' [کجا را میخواند دوم], N' بالانس شیت تلفیقی فرابورس' [کاربرد]
from P_CalcDayCountInBalanceSheetTalfighiCategurbalancesheet_FaraBourse
union all 
select N'BalancSheetTalfighi_DataBase_cashflow_Bourse.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'[BalanceSheetTalfighiCategurCashflow_Bourse]' [به کجا ارسال میشود], N'https://api.bourseview.com/v2/stocks/statements',cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180, (select top 1 cast(createdate as nvarchar(20)) from [BalanceSheetTalfighiCategurCashflow_Bourse] order by createdate desc) [آخرین زمان بروز رسانی],N'', N'' [کجا را میخواند], '' [کجا را میخواند دوم], N' کش فلو تلفیقی بورس' [کاربرد]
from P_CalcDayCountInBalanceSheetTalfighiCategurCashflow_Bourse
union all 
select N'BalancSheetTalfighi_DataBase_cashflow_FaraBourse.py' [اولین توضیح],N'تلفیقی های فرابورس باید چهار ماه گذشته شان فراخوانی شود تا بورس ویو داده بیاورد'  [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'[BalanceSheetTalfighiCategurCashflow_FaraBourse]' [به کجا ارسال میشود], N'https://api.bourseview.com/v2/stocks/statements',cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180, (select top 1 cast(createdate as nvarchar(20)) from [BalanceSheetTalfighiCategurCashflow_FaraBourse] order by createdate desc) [آخرین زمان بروز رسانی],N'', N'' [کجا را میخواند], '' [کجا را میخواند دوم], N' کش فلو تلفیقی فرابورس' [کاربرد]
from P_CalcDayCountInBalanceSheetTalfighiCategurCashflow_FaraBourse
union all 
select N'BalancSheetTalfighi_DataBase_incomeStatement_Bourse.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'BalanceSheetTalfighiCategurincomestatement_Bourse' [به کجا ارسال میشود], N'https://api.bourseview.com/v2/stocks/statements',cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180, (select top 1 cast(createdate as nvarchar(20)) from [BalanceSheetTalfighiCategurincomestatement_Bourse] order by createdate desc) [آخرین زمان بروز رسانی],N'', N'' [کجا را میخواند], '' [کجا را میخواند دوم], N' اینکام استیت منت تلفیقی بورس' [کاربرد]
from P_CalcDayCountInBalanceSheetTalfighiCategurincomestatement_Bourse


union all 
select N'BalancSheetTalfighi_DataBase_incomeStatement_FaraBourse.py' [اولین توضیح], N'تلفیقی های فرابورس باید چهار ماه گذشته شان فراخوانی شود تا بورس ویو داده بیاورد' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'BalanceSheetTalfighiCategurincomestatement_FaraBourse' [به کجا ارسال میشود], N'https://api.bourseview.com/v2/stocks/statements',cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180, (select top 1 cast(createdate as nvarchar(20)) from [BalanceSheetTalfighiCategurincomestatement_FaraBourse] order by createdate desc) [آخرین زمان بروز رسانی],N'', N'' [کجا را میخواند], '' [کجا را میخواند دوم], N' اینکام استیت منت تلفیقی بورس' [کاربرد]
from P_CalcDayCountInBalanceSheetTalfighiCategurincomestatement_FaraBourse

union all 
select  N'BalanceSheet_Gen_VPreBalanceSheetGheyreTalfighi_FaraBourse_Drop_Bilion.py' [اولین توضیح], N'در این ویو تنها میلیارد ها حذف میشوند و هیچ پردازش دیگری بر روی آن اتفاق نمی افتد.' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'VPreBalanceSheetGheyreTalfighi_FaraBourse_Drop_Bilion' [به کجا ارسال میشود], N'',cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180, (select top 1 cast(createdate as nvarchar(20)) from [VPreBalanceSheetGheyreTalfighi_FaraBourse_Drop_Bilion] order by createdate desc) [آخرین زمان بروز رسانی],N'', N'' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from P_CalcDayCountInVPreBalanceSheetGheyreTalfighi_FaraBourse_Drop_Bilion

union all
select N'BalanceSheet_Gen_VPreBalanceSheetGheyreTalfighi_Bourse_Drop_Bilion.py' [اولین توضیح], N'در این ویو تنها میلیارد ها حذف میشوند و هیچ پردازش دیگری بر روی آن اتفاق نمی افتد.' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'VPreBalanceSheetGheyreTalfighi_Bourse_Drop_Bilion' [به کجا ارسال میشود], N'',cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180, (select top 1 cast(createdate as nvarchar(20)) from [VPreBalanceSheetGheyreTalfighi_Bourse_Drop_Bilion] order by createdate desc) [آخرین زمان بروز رسانی],N'', N'' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from P_CalcDayCountInVPreBalanceSheetGheyreTalfighi_Bourse_Drop_Bilion

union all 
select  N'BalanceSheet_Gen_VPreBalanceSheetTalfighi_FaraBourse_Drop_Bilion.py' [اولین توضیح], N'در این ویو تنها میلیارد ها حذف میشوند و هیچ پردازش دیگری بر روی آن اتفاق نمی افتد.' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'VPreBalanceSheetTalfighi_FaraBourse_Drop_Bilion' [به کجا ارسال میشود], N'',cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180, (select top 1 cast(createdate as nvarchar(20)) from [VPreBalanceSheetTalfighi_FaraBourse_Drop_Bilion] order by createdate desc) [آخرین زمان بروز رسانی],N'', N'' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from P_CalcDayCountInVPreBalanceSheetTalfighi_FaraBourse_Drop_Bilion
)

select * from cte
