



CREATE   view [dbo].[SystemTest3]
as with cte3 as (

select N'BalanceSheet_Gen_VPreBalanceSheetTalfighi_Bourse_Drop_Bilion.py' [اولین توضیح], N'در این ویو تنها میلیارد ها حذف میشوند و هیچ پردازش دیگری بر روی آن اتفاق نمی افتد.' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'VPreBalanceSheetTalfighi_Bourse_Drop_Bilion' [به کجا ارسال میشود], N''ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180, (select top 1 cast(createdate as nvarchar(20)) from [VPreBalanceSheetTalfighi_Bourse_Drop_Bilion] order by createdate desc) [آخرین زمان بروز رسانی],N''[A], N'' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from P_CalcDayCountInVPreBalanceSheetTalfighi_Bourse_Drop_Bilion

union all 
select N'BalanceSheet_Gen_PreBalanceSheetTalfighi_Cashflow.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'BalanceSheetTalfighiCategurCashflow' [به کجا ارسال میشود], N'',cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180, (select top 1 cast(CreateDate as nvarchar(20)) from BalanceSheetTalfighiCategurCashflow_Bourse order by createdate desc) [آخرین زمان بروز رسانی],N'', N'BalanceSheetTalfighiCategurCashflow_Bourse' [کجا را میخواند], '' [کجا را میخواند دوم], N' بالانس شیت تلفیقی کش فلو' [کاربرد]
from P_CalcDayCountInBalanceSheetTalfighi_cashflow
union all 
select N'BalanceSheet_Gen_PreBalanceSheetGheyreTalfighi_Cashflow.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'BalanceSheetGheyreTalfighiCategurCashflow' [به کجا ارسال میشود], N'',cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180, (select top 1 cast(CreateDate as nvarchar(20)) from BalanceSheetGheyreTalfighiCategurCashflow_Bourse order by createdate desc) [آخرین زمان بروز رسانی],N'', N'BalanceSheetGheyreTalfighiCategurCashflow_Bourse' [کجا را میخواند], '' [کجا را میخواند دوم], N'بالانس شیت غیر  کش فلو تلفیقی' [کاربرد]
from P_CalcDayCountInBalanceSheetGheyreTalfighi_cashflow



union all 
select N'BalanceSheet_Gen_PreBalanceSheetGheyreTalfighi.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'GheyreTalfighi' [به کجا ارسال میشود], N'',cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180, (select top 1 cast(CreateDate as nvarchar(20)) from PreBalanceSheetGheyreTalfighi order by createdate desc) [آخرین زمان بروز رسانی],N'', N'PreBalanceSheetGheyreTalfighi' [کجا را میخواند], '' [کجا را میخواند دوم], N'بالانس شیت غیر تلفیقی' [کاربرد]
from P_CalcDayCountInBalanceSheetGheyreTalfighi
union all 
select N'BalanceSheet_Gen_PreBalanceSheetTalfighi.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'Talfighi' [به کجا ارسال میشود], N'',cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180, (select top 1 cast(CreateDate as nvarchar(20)) from PreBalanceSheetTalfighi order by createdate desc) [آخرین زمان بروز رسانی],N'', N'PreBalanceSheetTalfighi' [کجا را میخواند], '' [کجا را میخواند دوم], N'بالانس شیت تلفیقی' [کاربرد]
from P_CalcDayCountInBalanceSheetGheyreTalfighi
union all 
select N'BalanceSheet_Gen_VBalanceSheetGheyreTalfighi.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'VBalanceSheetNahayi' [به کجا ارسال میشود], N'',cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180, (select top 1 cast(CreateDate as nvarchar(20)) from VPreBalanceSheetGheyreTalfighi order by createdate desc) [آخرین زمان بروز رسانی],N'', N'' [کجا را میخواند], '' [کجا را میخواند دوم], N'بالانس شیت غیر تلفیقی' [کاربرد]
from P_CalcDayCountInBalanceSheetGheyreTalfighi
union all 
select N'TSETMCStackHoldersChanges.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'StackHoldersForLastDay1Mounth6Mounth' [به کجا ارسال میشود], N'http://www.tsetmc.com/Loader.aspx?ParTree=15131I&t=1' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180, (select top 1 cast(CreateDate as nvarchar(100)) from StackHolders order by CreateDate desc) [آخرین زمان بروز رسانی],N'اطلاعات مربوط به تغییر مالکیت سهامداران عمده در ویوی [dbo].StackHoldersForLastDay1Mounth6Mounth]نمایش داده میشود به شکلی که تغییرات مالکیت سهامداران عمده در روز کاری گذشته و در سی روز گذشته و در شش ماه گذشته را نمایش میدهد' [Mostanadat], N'' [کجا را میخواند], '' [کجا را میخواند دوم], N'سهامدار عمده' [کاربرد]
from P_CalcDayCountInStackHolders
union all 
select N'faraBourse.py' [اولین توضیح], N'AmareOraghFaraBourse' [توضیح دوم], N'AmareBazareBaazFaraBourse' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'VChartayi' [به کجا ارسال میشود], N'https://www.ifb.ir/datareporter/DailySukukTrades.aspx' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from AmareOraghFaraBourse order by createdate desc) [آخرین زمان بروز رسانی],N'Etelaate Marbout be Amare Oraghe Mosharekat ke Tavasote Farabourse Montasher Mishavad. Dar Chartayi Namayesh Dade Mishavad Be Onvane Yek Radif. Yani Radif hay Bank Markazi va Dolat va Bankha va Sandogh ha Va SayerAshkhas be chartayi Ezafe Mishavad. Va Hamchenin Arzeshe Moamelat Be Sourate Tarikhi niz Jaam Zade Mishavad. Mesle 365DaysVolume va Hamchenin Az Anjayi Ke Farabours in Etelaat Ra Be Tafkike Mizane Kharid Va Mizane Foroush Montasher Mikonad. Yani Masalan Migouyad Che Mizan Oragh Tavasout Bank Markazi Kharide Shode Ast Va Che Mizan Foroukhte Shode Ast Ma Niz Sotun 365DaysVolumeSell Ra Baraye Foroush Darim Va Sotune 365DaysVolume Ra Baraye Kharid. (https://www.ifb.ir/datareporter/DailySukukTrades.aspx)' [Mostanadat], N'' [کجا را میخواند], '' [کجا را میخواند دوم], N'اوراق فرابورس' [کاربرد]
from [P_CalcDayCountInAmareOraghFaraBourse]
union all 



select N'ValuesOfTradePeriodicly_Light_DataBase.py' [اولین توضیح], N'طبق توافقات صورت گرفته منظور از سه روز، سه روز کاری است' [توضیح دوم], N'منظور از هفت روز هفت روز کاری است' [توضیح سوم],N'منظور از چهارده روز گذشته چهارده روز کاری هست و بقیه هم همینطور به غیر از سه ماه و شش ماهه و یک ساله که تقویمی منظور است البته این ها برای سهام معامله شده است'[توضیح چهارم],N'ارزش بازار ها کاملا تقویمی منظور است اما اگر در آن روز تعطیلی سراسری بوده باشد اولین روز کاری بعد در نظر گرفته میشود'[توضیح پنجم],N' نگته دیگر اینکه اگر تعطیلی سراسری نباشد بلکه یک نماد ممنون متوقف باشد یا به هر دلیل دیگری داده نداشته باشد ان نماد با ارزش بازار صفر نمایش داده میشود و رشدش هم نسبت به آن بازه زمانی صفر در نظر گرفته میشود'[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'VChartayiPreProcess' [به کجا ارسال میشود], N'HistoricalChartayi' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from HistoricalChartayi order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'' [کجا را میخواند], '' [کجا را میخواند دوم], N'هیستوری چهارتایی' [کاربرد]
from P_CalcDayCountInHistoricalChartayi
union all 
select N'ValuesOfTradePeriodicly_Light_DataBase.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'VChartayi' [به کجا ارسال میشود], N'vChartayiPreProcess' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from VChartayi order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'VChartayiPreProcess' [کجا را میخواند], 'ForConvert اطلاعات ثابت' [کجا را میخواند دوم], N'پری پروسس چهارتایی' [کاربرد]
from P_CalcDayCountInHistoricalChartayi

union all 
select N'BourseView_Indeustry_Company.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'VChartayi' [به کجا ارسال میشود], N'vChartayiPreProcess' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from VIndustries order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'VChartayiPreProcess' [کجا را میخواند], 'ForConvert اطلاعات ثابت' [کجا را میخواند دوم], N'پری پروسس چهارتایی' [کاربرد]
from P_CalcDayCountInIndustries)
select * from cte3
