

CREATE   view [dbo].[SystemTest4] 
as with  cte4 as (








select N'اطلاعات تاریخی هر شب از جدول HistoricalChartayi خوانده و پردازش میشود و در جدول temp نگهداشته میشود ' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'VChartayi' [به کجا ارسال میشود], N'temp' ReportName,cast(N'' as nvarchar(20)) CNT365,cast(N'' as nvarchar(20)) CNT90,cast(N'' as nvarchar(20)) CNT30,cast(N'' as nvarchar(20)) CNT14,cast(N'' as nvarchar(20)) CNT7,cast(N'' as nvarchar(20)) CNT3,cast(N'' as nvarchar(20)) CNT180,(select  top 1 cast(RunTimeStamp as nvarchar(20)) from v_JobStatus where jobname = N'SchaduledJobs' order by RunTimeStamp desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'HistoricalChartayi' [کجا را میخواند], 'calculateHistoricalData پروسیجر' [کجا را میخواند دوم], N'پری پروسس چهارتایی' [کاربرد]


union all 
select N'این ویو نیست و جدول است،‌بخاطر افزایش پرفرمنس جدول شده است از ویوی VChartayiPreProcess اطلاعات را استخراج میکند  ' [اولین توضیح], N'اطلاعات تاریخی گذشته هر شب یکبار محاسبه میشود و در جدول temp نگهداشته میشود همچنین بعد از هر بار مراجعه به سایت بورس ویو یکبار تریگر استارت تریگر فایر میشود' [توضیح دوم], N'در مورد داده های تاریخی به روز های تقویمی نگاه میکنیم به شرط اینکه روز مورد نظر تعطیل نباشد یعنی اگر میگوییم ۴ ماه قبل یعنی دقیقا ۳ ماه تقویمی به گذشته میرویم و اگر روز کاری بود همان روز را در نظر میگیریم اگر تعطیل بود روز بعدش' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'VChartayi' [به کجا ارسال میشود], N'Chartayi' ReportName,cast([365] as nvarchar(20))[365],cast([90]as nvarchar(20))[90],cast([30]as nvarchar(20))[30],cast([14]as nvarchar(20))[14],cast([7]as nvarchar(20))[7],cast([3]as nvarchar(20))[3],cast([180]as nvarchar(20))[180],cast((select top 1 createDate from VChartayi order by createdate desc)as nvarchar(100)) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'' [کجا را میخواند], '' [کجا را میخواند دوم], N'چهارتایی جانی' [کاربرد]
from vTestChartayi
union all 

select N'جمع بالانس شیت تلفیقی و غیر تلفیقی نمایش داده میشود واگر اطلاعات تلفیقی جدید داشته باشد همان اطلاعات نمایش داده میشود و اگر غیر تلفیقی جدید باشد نیز اطلاعات غیر تلفیقی نمایش داده میشود یعنی اولویت با جدیدتر است' [اولین توضیح], N'غیر تلفیقی هایی که تلفیقی وجود ندارد برای آنها که سود خالص تعدیل شده یک ساله آن ها بیشتر باشد از غیر تلفیقی' [توضیح دوم], N'و همچنین تلفیقی هایی که غیر تلفیقی وجود ندارد برای آنها که سود خالص تعدیل شده یک ساله آن ها بیشتر باشد از تلفیقی' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'VBalanceSheetGheyreTalfighi' [به کجا ارسال میشود], N'BalanceSheetGheyreTalfighi' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(CreateDate as nvarchar(20)) from VPreBalanceSheetGheyreTalfighi order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'' [کجا را میخواند], '' [کجا را میخواند دوم], N'بالانس شیت جانی' [کاربرد]
from [P_CalcDayCountInAmareOraghFaraBourse]
union all 
select N'جمع بالانس شیت تلفیقی و غیر تلفیقی نمایش داده میشود واگر اطلاعات تلفیقی جدید داشته باشد همان اطلاعات نمایش داده میشود و اگر غیر تلفیقی جدید باشد نیز اطلاعات غیر تلفیقی نمایش داده میشود یعنی اولویت با جدیدتر است'  [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'VBalanceSheetGheyreTalfighi' [به کجا ارسال میشود], N'BalanceSheet' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(CreateDate as nvarchar(20)) from VPreBalanceSheetGheyreTalfighi order by createdate desc)  [آخرین زمان بروز رسانی],N'' [Mostanadat], N'' [کجا را میخواند], '' [کجا را میخواند دوم], N'بالانس شیت جانی' [کاربرد]
from [P_CalcDayCountInAmareOraghFaraBourse]
union all 
select N'این ویو نیست و جدول است،‌بخاطر افزایش پرفرمنس جدول شده است' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'VChartayi' [به کجا ارسال میشود], N'AmarBazarBazFarabourse' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from VChartayi order by createdate desc) [آخرین زمان بروز رسانی],N'Etelaate Marbout Be Amaliat Bazare Baz Ke Farabourse Montasher mikonad, Va In Etelaat Tahte Onvane Sotoun ha Dar Moghable Radif Bank Markazi Namayesh Dade Mishavad, Onvan Haye BazareBaaz, Saayer, PazireNevisi Dolati 3 Meghdari Hastand ke Montasher Mishavand. Hamchenin In Meghdar Ha Be Sourate Tarikhi Niz Namayesh Dade Mishvand  (https://www.ifb.ir/datareporter/DailySukukTrades.aspx)' [Mostanadat], N'' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInAmareBazareBaazFaraBourse]
union all 
select N'' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'' [به کجا ارسال میشود], N'-',N'-',N'-',N'-',N'-',N'-',N'-',N'-',N'-',N'', N'' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
union all 
select N'EconomistAndazeAslTavarrom.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'AndazeAslTavarom' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from AndazeAslTavarom order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/core-inflation-rate' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInAndazeAslTavarom]
union all 
select N'EconomistBankMarkazi.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'BankMarkazi' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from BankMarkazi order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/central-bank-balance-sheet' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInBankMarkazi]
union all 
select N'EconomistBedehiDolatBeTolidNakhales.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'BedehiDolatBeTolidNakhales' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from BedehiDolatBeTolidNakhales order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/government-debt-to-gdp' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInBedehiDolatBeTolidNakhales]
union all 
select N'EconomistBedehiKhanevarBeDaramad.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'BedehiKhanevarBeDaramad' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from BedehiKhanevarBeDaramad order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/households-debt-to-income' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInBedehiKhanevarBeDaramad]
union all 
select N'EconomistBedehiKhanevarBeTolidNakhales.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'BedehiKhanevarBeTolidNakhales' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from BedehiKhanevarBeTolidNakhales order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/households-debt-to-gdp' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInBedehiKhanevarBeTolidNakhales]
union all 
select N'EconomistBedehikhareji.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'BedehiKhareji' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from BedehiKhareji order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/external-debt' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInBedehiKhareji]
union all 
select N'EconomistBourse.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'‌' [به کجا ارسال میشود], N'Bourse' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from Bourse order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/stocks' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInBourse]
union all 
select N'EconomistBourseEnglis.py' [اولین توضیح], N'اطلاعات سال 2005 نیز بصورت ثابت از جدول BourseEnglis2005 خوانده میشود' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'VBoursEnglis' [به کجا ارسال میشود], N'BoursEnglis' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from BoursEnglis order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/united-kingdom/stock-market' [کجا را میخواند], 'BourseEnglis2005' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInBoursEnglis])
select * from cte4
