

--select * from systemtest7

CREATE view [dbo].[systemtest8] 
as 
with cte8 as (
select N'EconomistBedehiDolatBeTolidNakhales.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'BedehiDolatBeTolidNakhales' [به کجا ارسال میشود], N'BedehiDolatBeTolidNakhales' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from BedehiDolatBeTolidNakhales order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/government-debt-to-gdp' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInBedehiDolatBeTolidNakhales]
union all 
select N'EconomistBedehiHayeKhosusiBeTolidNakhalesDakheli.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'BedehiHayeKhosusiBeTolidNakhalesDakheli' [به کجا ارسال میشود], N'BedehiHayeKhosusiBeTolidNakhalesDakheli' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from BedehiHayeKhosusiBeTolidNakhalesDakheli order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/private-debt-to-gdp' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInBedehiHayeKhosusiBeTolidNakhalesDakheli]
union all 
select N'EconomistBedehiKhanevarBeDaramad.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'BedehiKhanevarBeDaramad' [به کجا ارسال میشود], N'BedehiKhanevarBeDaramad' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from BedehiKhanevarBeDaramad order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/households-debt-to-income' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInBedehiKhanevarBeDaramad]
union all 
select N'EconomistBedehiKhanevarBeTolidNakhales.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'BedehiKhanevarBeTolidNakhales' [به کجا ارسال میشود], N'BedehiKhanevarBeTolidNakhales' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from BedehiKhanevarBeTolidNakhales order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/households-debt-to-gdp' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInBedehiKhanevarBeTolidNakhales]
union all 
select N'EconomistBedehiKhareji.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'BedehiKhareji' [به کجا ارسال میشود], N'BedehiKhareji' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from BedehiKhareji order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/external-debt' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInBedehiKhareji]
union all 
select N'EconomistAndazeAslTavarom.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'AndazeAslTavarom' [به کجا ارسال میشود], N'AndazeAslTavarom' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from AndazeAslTavarom order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/core-inflation-rate' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInAndazeAslTavarom]
union all 
select N'EconomistMaliatBarForoush.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'MaliatBarForoush' [به کجا ارسال میشود], N'MaliatBarForoush' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from MaliatBarForoush order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/sales-tax-rate' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInAndazeAslTavarom]
union all 
select N'EconomistBoursePortugal.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'BoursPortugal' [به کجا ارسال میشود], N'BoursPortugal' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from BoursPortugal order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/Portugal/stock-market' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInBoursPortugal]
union all 
select N'EconomistBourseMalaysia.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'BoursMalaysia' [به کجا ارسال میشود], N'BoursMalaysia' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from BoursMalaysia order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/Malaysia/stock-market' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInBoursMalaysia]
union all 
select N'EconomistHadeAghalDastmozd.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'HadeAghalDastmozd' [به کجا ارسال میشود], N'HadeAghalDastmozd' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from HadeAghalDastmozd order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/minimum-wages' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInHadeAghalDastmozd]
union all 
select N'EconomistMovazeneTejari.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'MovazeneTejari' [به کجا ارسال میشود], N'MovazeneTejari' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from MovazeneTejari order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/balance-of-trade' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInMovazeneTejari]
union all 
select N'EconomistMaliatBarForoush.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'MaliatBarForoush' [به کجا ارسال میشود], N'MaliatBarForoush' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from MaliatBarForoush order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/country-list/sales-tax-rate' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInMaliatBarForoush]
union all 
select N'EconomistBourseBrazil.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'boursbrazil' [به کجا ارسال میشود], N'boursbrazil' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from boursbrazil order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/brazil/stock-market' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInboursbrazil]
union all 
select N'Economistboursespain.py' [اولین توضیح], N'' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'boursspain' [به کجا ارسال میشود], N'boursspain' ReportName,cast(CNT365 as nvarchar(20)) CNT365,cast(CNT90 as nvarchar(20)) CNT90,cast(CNT30 as nvarchar(20)) CNT30,cast(CNT14 as nvarchar(20)) CNT14,cast(CNT7 as nvarchar(20)) CNT7,cast(CNT3 as nvarchar(20)) CNT3,cast(CNT180 as nvarchar(20)) CNT180,(select top 1 cast(createdate as nvarchar(20)) from boursspain order by createdate desc) [آخرین زمان بروز رسانی],N'' [Mostanadat], N'https://fa.tradingeconomics.com/spain/stock-market' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]
from [P_CalcDayCountInboursspain]
union all 
select N'Backup_and_Compress.py' [اولین توضیح], N'آخرین بک اپ نگهداری میشود و مابقی حذف میشود' [توضیح دوم], N'' [توضیح سوم],N''[توضیح چهارم],N''[توضیح پنجم],N''[توضیح ششم],N''[توضیح هفتم],N''[توضیح هشتم],N''[توضیح نهم], N'systemtest' [به کجا ارسال میشود], N'systemtest' ReportName,cast(N'' as nvarchar(20)) CNT365,cast(N'' as nvarchar(20)) CNT90,cast(N'' as nvarchar(20)) CNT30,cast(N'' as nvarchar(20)) CNT14,cast(N'' as nvarchar(20)) CNT7,cast(N'' as nvarchar(20)) CNT3,cast(N'' as nvarchar(20)) CNT180,N'' [آخرین زمان بروز رسانی],N'' [Mostanadat], N'' [کجا را میخواند], '' [کجا را میخواند دوم], N'' [کاربرد]

)
select * 
 from cte8
